before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: U73xZyxU3aAMgHJJujatqNG/ng+PcMzMHNRGHPrz8ILA9vfspjUzh7sScQXm14hJmYyCYDPtI2b7fhlq4gHijRwtmM0mKR4Jm+KoZ7V9O1xB6seoYyPBlwvLfPu2y0xS8enrAaf3+Ctm7HkDJxUAqvA8b9hO/qQEfGMSQMkV+zi/OU9DPaCZaEOU1LyJQ7OSZImDP1l8U7v1+EYNbCBzJCIiU4SLlSMUo7ttx0ECq9YJfhoodp0WOTCl1uXfuUpZgP03AskjuV/n66WRMvFQXz6WEA3QzzLZI5MMTu+Cm/pSAXBcWueMA9a9pSLsK48VUlrii5PruQ0stFCgMapIkv8qlSUcGcs4Fj4mJnX+vhaUEk8kMRq2W1bMbfd/M2cSSS5IkG203debyKT7x0MSqD369JiiMJAB8CXFtXfRiVGeWPioroBNvDa9gftOSVapfu4nwUsi5AAnYXvlJ/oxALDOG16Rl3auoZgLezsuy4+c1OG7WZ9kqJ3Ujisxwlxb8OeqqMTuz9UEQExAKFd05BNk4k+H10R99S89xB9SZrmgHS8l+JzocsqjBZcCF8N+6NaYr7uUgcm1RsoR7itHoAhK/LJvxOnr9OHKGYYH1qhY6YE4lGgSTUa0ghX+VXGe0QS9VESXhhTfMjE/R0qBU+vLe9VGmpddvRUUGjKBlTA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
